# Generated by Django 5.1.7 on 2025-03-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_subscribed', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='webflow_int_email_5e21c6_idx'), models.Index(fields=['platform'], name='webflow_int_platfor_114aac_idx')],
            },
        ),
    ]
