# Generated by Django 5.1.7 on 2025-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webflow_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betauser',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='betauser',
            name='newsletter_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='betauser',
            index=models.Index(fields=['confirmation_token'], name='webflow_int_confirm_b605d7_idx'),
        ),
    ]
